# -*- coding: utf-8 -*-
"""map_marker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiZdWUNnCO-W7W0loAplq62yRAKQDRzv
"""

import streamlit as st
import folium
from streamlit_folium import folium_static

st.title("Map Marker App")

# User input for coordinates
lat = st.number_input("Enter Latitude:", value=37.7749, format="%.6f")
lon = st.number_input("Enter Longitude:", value=-122.4194, format="%.6f")

# Create a map centered at the input coordinates
m = folium.Map(location=[lat, lon], zoom_start=12)

# Add a marker to the map
folium.Marker(
    [lat, lon],
    popup=f"Location: {lat}, {lon}",
    tooltip="Click for details",
    icon=folium.Icon(color="blue")
).add_to(m)

# Display the map in the Streamlit app
folium_static(m)